In [ ]:
from sklearn.datasets import load_iris
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
# Add noise to dataset to simulate difficulty
np.random.seed(42)
X_noisy = X + np.random.normal(0, 0.5, X.shape)
# Train-test split (different seed to vary split)
X_train, X_test, y_train, y_test = train_test_split(X_noisy, y, test_size=0.3, random_state=42)
# BAGGING
bagging_model = BaggingClassifier(
 estimator=DecisionTreeClassifier(),
 n_estimators=50,
 random_state=1
)
bagging_model.fit(X_train, y_train)
bagging_preds = bagging_model.predict(X_test)
# BOOSTING
boosting_model = AdaBoostClassifier(
 estimator=DecisionTreeClassifier(max_depth=1),
 n_estimators=50,
 random_state=1
)
boosting_model.fit(X_train, y_train)
boosting_preds = boosting_model.predict(X_test)
def evaluate_model(name, y_true, y_pred):
 print(f"\n{name} Results:")
 print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
 print("Confusion Matrix:")
 print(confusion_matrix(y_true, y_pred))
 print("Classification Report:")
 print(classification_report(y_true, y_pred, target_names=iris.target_names))
# Run evaluations
evaluate_model("Bagging", y_test, bagging_preds)
evaluate_model("Boosting", y_test, boosting_preds)


Bagging Results:
Accuracy: 0.8667
Confusion Matrix:
[[19  0  0]
 [ 0 10  3]
 [ 0  3 10]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.77      0.77      0.77        13
   virginica       0.77      0.77      0.77        13

    accuracy                           0.87        45
   macro avg       0.85      0.85      0.85        45
weighted avg       0.87      0.87      0.87        45


Boosting Results:
Accuracy: 0.8222
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  8  5]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.62      1.00      0.76        13
   virginica       1.00      0.38      0.56        13

    accuracy                           0.82        45
   macro avg       0.87      0.79      0.77        45
weighted avg       0.89      0.82      0.80        45

